theme= "vienna"
BaseUrl= "http://10.0.3.84:1313/"
LanguageCode= "en-EN"
Title= "l33tsource"
paginate = 5
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "Sometimes random blog posts appear."
  cover = "images/cover.jpg"
  author = "l33tname"
  authorlocation = "Berlin, Germany"
  githubName = "fliiiix"
  twitterName = "l33tname"